package fixtures

// Code generated by scripts/generate_modules_from_liquibase; DO NOT EDIT.
// Source: backend-service/web/src/main/resources/db/changelog

type ModuleSeed struct {
	ID          string
	Name        string
	Description string
}

// LiquibaseModules is the current module catalog after inserts, deletes, and renames.
var LiquibaseModules = []ModuleSeed{
	{ID: "10125362-126c-066b-b768-4cd888b2626b", Name: "AGENT", Description: "Notifications for agent related alerts. Includes alerts for unhealthy agents when they stop reporting health for more than 10 minutes, indicating potential connectivity or configuration issues."},
	{ID: "10125382-12cc-4b9b-b728-4cd888b2625b", Name: "BACKEND", Description: "Other system and service alerts"},
	{ID: "11025382-12cc-4b9b-b728-4cd888b2625b", Name: "CLOUD_LOG_SOURCE", Description: "Notifications for sources collected using cloud collectors.  Typical alerts include silent data sources, lower volume trends. "},
	{ID: "11225382-12cc-4b9b-b728-4cd888b2625b", Name: "CONNECTOR", Description: "Notifications for connector health."},
	{ID: "10525382-12cc-4b9b-b728-4cd888b2625b", Name: "DAILY_DIGEST", Description: "Notifications to receive daily health digest emails. Daily digest emails give a quick overview of your environment from the last 24 hours."},
	{ID: "11125382-12cc-4b9b-b728-4cd888b2625b", Name: "DESTINATION", Description: "Notifications for destinations. Typical alerts include destination unavailability, authentication/authorization alerts. "},
	{ID: "10125362-126c-016b-b768-4cd888b2626b", Name: "ENRICHMENT", Description: "Notifications for enrichment processes. Includes deployment issues, configuration errors when in ERRORED state, and low success rate alerts when success rate drops below 50%."},
	{ID: "10225382-12cc-4b9b-b728-4cd888b2625b", Name: "FLEET", Description: "Notifications for Fleet and edge node level alerts. Includes node unavailability, hardware utilization type of alerts from the edge nodes and fleet."},
	{ID: "10725382-12cc-4b9b-b728-4cd888b2625b", Name: "FLEET_NODE", Description: "Notifications to receive granular alerts for edge nodes configured in your environment"},
	{ID: "10125362-126c-026b-b768-4cd888b2626b", Name: "INSIGHTS_RULE", Description: "Notifications for insights rule processing. Includes alerts for insights rule deployment issues when staying in DEPLOYING state for more than 15 minutes and configuration errors when insights rule goes into ERRORED state."},
	{ID: "10825382-12cc-4b9b-b728-4cd888b2625b", Name: "LOG_SOURCE", Description: "Notifications for sources collected using the edge nodes. Typical alerts include silent data sources, lower volume trends. "},
	{ID: "10125362-126c-046b-b768-4cd888b2626b", Name: "LOOKUP", Description: "Notifications for lookup operations. Includes alerts for lookup deployment issues when staying in DEPLOYING state for more than 15 minutes and configuration errors when lookup goes into ERRORED state."},
	{ID: "10125362-126c-036b-b768-4cd888b2626b", Name: "ROUTE_PROCESSOR", Description: "Notifications for route processor operations. Includes alerts for route processor deployment issues when staying in DEPLOYING state for more than 15 minutes and configuration errors when route processor goes into ERRORED state."},
	{ID: "10125362-126c-056b-b768-4cd888b2626b", Name: "TRANSFORMATION", Description: "Notifications for transformation processes. Includes deployment issues, configuration errors when in ERRORED state, and Sentinel transformation conflicts with missing fields or data type mismatches."},
	{ID: "10125362-126c-4b6b-b768-4cd888b2626b", Name: "VOLUME_CONTROL", Description: "Notifications for volume control alerts. It includes alerts related to volume reductions and volume control rules."},
	{ID: "10625382-12cc-4b9b-b728-4cd888b2625b", Name: "WEEKLY_DIGEST", Description: "Notifications to receive weekly health digest emails. Weekly digest emails give a quick overview of your environment from the last 7 days ."},
}
