package constants

const Broker = "replay.bootstrap_brokers"
const ClusterName = "data-replay-cluster"
const DataReplayProducer = "data-replay-producer"
const DataReplayStatusProducer = "data-replay-status-producer"
const DataSequenceProducer = "data-event-sequence-producer"
const KafkaBootstrapServers = "KafkaBootstrapServers"
const SequenceBucket = "s3.events.bucket"
const SequenceBucketPrefix = "s3.events.bucket"
const StatsTopic = "db.replay.status"

const Tags = "tags"
const TenantID = "db_tenant_id"
const DeviceType = "db_device_type"
const EventSourceId = "db_event_source_id"
const ServiceName = "service_name"
const ServiceVersion = "service_version"
const EdgeId = "db_edge_id"
const EventDependencyId = "db_event_dependency_id"
const ConnectorId = "db_connector_id"
const DestinationId = "destination_id"
const PipelineId = "pipeline_id"
const RuleId = "rule_id"
const EventId = "db_event_id"
const EdgeTimestamp = "db_edge_ts"
const RuleType = "rule_type"
const ErrorCode = "error_code"
const DestinationType = "destination_type"
const FleetId = "db_fleet_id"

const ComponentName = "db_component_name"
const DeviceVendor = "db_device_vendor"
const LogType = "db_log_type"
