name: Go Build and Scan

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - name: Configure Git for private repositories
        run: |
          git config --global url."https://${{ secrets.RELEASE_ACCESS_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Configure Go for private modules
        run: |
          echo "machine github.com login ${{ secrets.RELEASE_ACCESS_TOKEN }}" > ~/.netrc
          echo "machine api.github.com login ${{ secrets.RELEASE_ACCESS_TOKEN }}" >> ~/.netrc
          chmod 600 ~/.netrc  # Ensure the .netrc file has the correct permissions

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build with Go
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_ACCESS_TOKEN }}  # Set the custom token as an environment variable
        run: |
          go build -tags musl -o databahn-jobs main.go

      - name: Black Duck Scan
        env:
          BLACKDUCK_URL: ${{ vars.BLACKDUCK_URL }}
          BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          DETECT_PROJECT_VERSION_NAME: ${{ github.ref_name }}
          DETECT_CODE_LOCATION_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}
        run: |
          curl -fLsS -o ${{ runner.temp }}/detect10.sh https://detect.blackduck.com/detect10.sh
          chmod +x ${{ runner.temp }}/detect10.sh
          ${{ runner.temp }}/detect10.sh