name: Master Branch CI

on:
  push:
    branches:
      - master

jobs:
  master:
    uses: databahn-ai/ci-github-workflows/.github/workflows/build-go-service.yaml@master
    with:
      service_name: ${{ github.event.repository.name }}
      service_version: "v${{ github.sha }}"
    secrets: inherit

  update-gitops-repo:
    needs:
      - master
    uses: databahn-ai/ci-github-workflows/.github/workflows/update-gitops-repo.yaml@master
    with:
      service_name: ${{ github.event.repository.name }}
      service_version: "v${{ github.sha }}"
      gitops_repo: "master"
      service_type: "scheduled"
    secrets: inherit
    
