name: Release CI Workflow

on:
  push:
    branches:
      - release/**
      - data_replay_fixes_priority_1/master

jobs:
  build-service:
    uses: databahn-ai/ci-github-workflows/.github/workflows/build-go-service.yaml@master
    with:
      service_name: ${{ github.event.repository.name }}
      service_version: "v${{ github.sha }}"
    secrets: inherit
