name: Tag Master

on:
  push:
    branches:
      - master
      - DB-29138-credential-manager-impl

jobs:
  tag:
    uses: databahn-ai/ci-github-workflows/.github/workflows/tag-master.yaml@master
    secrets: inherit
