name: Production Release Workflow

on:
  release:
    types: [ published ]
  push:
    branches:
      - release/*
jobs:
  release:
    uses: databahn-ai/ci-github-workflows/.github/workflows/build-go-service.yaml@master
    with:
      service_name: ${{ github.event.repository.name }}
      service_version: ${{ github.event.release.name }}
    secrets: inherit